import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";

const outfit = Outfit({subsets:['latin']});

export const metadata = { 
  title: "Ai Courese Generator Plateform",
  description : "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Toaster/>
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
