export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-10">
      <h1 className="text-3xl font-bold mb-6">Disclaimer</h1>
      <p className="mb-4">Last updated: May 4, 2025</p>

      <p className="mb-4">The content generated by AI Course Generator is for informational and educational purposes only. We make no warranties about its accuracy or completeness.</p>

      <p className="mb-4">We are not liable for any actions taken based on content generated from this platform. You are responsible for verifying and applying content as needed.</p>

      <p className="mb-4">We reserve the right to modify or remove features at any time without prior notice.</p>
    </div>
  );
}
